In [1]:
import yfinance as yf

#ticker: 종목 식별 코드 (예: 애플은 AAPL)
#microsoft에 대한 ticker 객체 생성
msft = yf.Ticker("MSFT")

#ticker 객체의 정보 출력
display(msft.info)

{'address1': 'One Microsoft Way',
 'city': 'Redmond',
 'state': 'WA',
 'zip': '98052-6399',
 'country': 'United States',
 'phone': '425 882 8080',
 'website': 'https://www.microsoft.com',
 'industry': 'Software - Infrastructure',
 'industryKey': 'software-infrastructure',
 'industryDisp': 'Software - Infrastructure',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': "Microsoft Corporation, a technology company, develops and supports a portfolio of technology solutions for individuals and businesses worldwide. Its products include operating systems, server applications, business solution applications, software development tools, desktop and server management tools, and video games; and devices, such as PCs, tablets, gaming and entertainment consoles, other intelligent devices, and related accessories. The company's Productivity and Business Processes segment offers Microsoft 365 Commercial, Enterprise Mobility + Security, Power BI, Exchange, SharePoint, Microsoft Teams, Microsoft 365 Security and Compliance, Microsoft 365 Copilot, and Windows Commercial on-premises and Office licensed on-premises. This segment also provides Microsoft 365 Consumer products and cloud services; LinkedIn, including talent solutions, marketing solutions, subscriptions, and sales solutions; Dynamics 365, a set of cloud-based applications; and on-premises ERP and CRM applications. Its Intelligent Cloud segment offers server products and cloud services; cloud and AI consumption-based services, GitHub cloud services, health and life sciences cloud services, as well as virtual desktop offerings, and other cloud services; SQL Server, Windows Server, Visual Studio, System Center, and related client access licenses; and enterprise support services, industry solutions, Microsoft partner network, and learning experience. The company's More Personal Computing segment provides Windows OEM licensing and devices comprising Surface and PC accessories; XBOX hardware, and XBOX first- and third-party content and services; XBOX Game Pass and other subscriptions; XBOX Cloud Gaming, advertising, and other cloud services; and search advertising consisting of Bing, Copilot, Microsoft News, Microsoft Edge, and third-party affiliates. It sells its products through partners and retail networks. The company was founded in 1975 and is headquartered in Redmond, Washington.",
 'fullTimeEmployees': 223000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Satya  Nadella',
   'age': 58,
   'title': 'Chairman & CEO',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 12251294,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Bradford L. Smith LCA',
   'age': 66,
   'title': 'President & Vice Chairman',
   'yearBorn': 1959,
   'fiscalYear': 2025,
   'totalPay': 4532750,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Amy E. Hood',
   'age': 53,
   'title': 'Executive VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 4444191,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Takeshi  Numoto',
   'age': 54,
   'title': 'Executive VP & Chief Marketing Officer',
   'yearBorn': 1971,
   'fiscalYear': 2025,
   'totalPay': 2871250,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Judson B. Althoff',
   'age': 52,
   'title': 'Executive VP & CEO of Commercial Business',
   'yearBorn': 1973,
   'fiscalYear': 2025,
   'totalPay': 4490115,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Carolina  Dybeck Happe',
   'age': 53,
   'title': 'Executive VP & COO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Alice L. Jolla',
   'age': 59,
   'title': 'Corporate VP & Chief Accounting Officer',
   'yearBorn': 1966,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Matthew  Kerner',
   'title': 'CTO & Corporate VP of Worldwide Sales and Solutions',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Jonathan  Neilson',
   'title': 'Vice President of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Jonathan M. Palmer',
   'title': 'Corporate Vice President & Chief Legal Officer',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 9,
 'boardRisk': 7,
 'compensationRisk': 5,
 'shareHolderRightsRisk': 2,
 'overallRisk': 5,
 'governanceEpochDate': 1788220800,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://www.microsoft.com/investor/default.aspx',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 509.22,
 'open': 508.13,
 'dayLow': 502.4,
 'dayHigh': 513.64,
 'regularMarketPreviousClose': 509.22,
 'regularMarketOpen': 508.13,
 'regularMarketDayLow': 502.4,
 'regularMarketDayHigh': 513.64,
 'dividendRate': 3.92,
 'dividendYield': 0.77,
 'exDividendDate': 1795046400,
 'payoutRatio': 0.1983,
 'fiveYearAvgDividendYield': 0.79,
 'beta': 1.108,
 'trailingPE': 28.322762,
 'forwardPE': 21.496983,
 'volume': 20020164,
 'regularMarketVolume': 20020164,
 'averageVolume': 29345579,
 'averageVolume10days': 23899620,
 'averageDailyVolume10Day': 23899620,
 'bid': 507.03,
 'ask': 515.0,
 'bidSize': 4,
 'askSize': 1,
 'marketCap': 3779305668608,
 'nonDilutedMarketCap': 3717153817339,
 'fiftyTwoWeekLow': 349.2,
 'fiftyTwoWeekHigh': 553.72,
 'allTimeHigh': 555.45,
 'allTimeLow': 0.088542,
 'fulldayPrice': 507.25,
 'fulldayChange': -1.6399841,
 'fulldayChangePercent': -0.3222226,
 'priceToSalesTrailing12Months': 11.388973,
 'fiftyDayAverage': 480.253,
 'twoHundredDayAverage': 432.2989,
 'trailingAnnualDividendRate': 3.64,
 'trailingAnnualDividendYield': 0.0071481876,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 3831275716608,
 'profitMargins': 0.40305,
 'floatShares': 7414407173,
 'sharesOutstanding': 7425545491,
 'sharesShort': 67346414,
 'sharesShortPriorMonth': 68544953,
 'sharesShortPreviousMonthDate': 1786665600,
 'dateShortInterest': 1789430400,
 'sharesPercentSharesOut': 0.0091,
 'heldPercentInsiders': 0.00092,
 'heldPercentInstitutions': 0.75801,
 'shortRatio': 3.21,
 'shortPercentOfFloat': 0.0091,
 'impliedSharesOutstanding': 7425545491,
 'bookValue': 59.565,
 'priceToBook': 8.544615,
 'lastFiscalYearEnd': 1782777600,
 'nextFiscalYearEnd': 1814313600,
 'mostRecentQuarter': 1782777600,
 'earningsQuarterlyGrowth': 0.313,
 'netIncomeToCommon': 133748998144,
 'trailingEps': 17.97,
 'forwardEps': 23.67588,
 'pegRatio': 1.65,
 'lastSplitFactor': '2:1',
 'lastSplitDate': 1045526400,
 'enterpriseToRevenue': 11.546,
 'enterpriseToEbitda': 19.725,
 '52WeekChange': -0.017356873,
 'SandP52WeekChange': 0.14299083,
 'lastDividendValue': 0.91,
 'lastDividendDate': 1787184000,
 'quoteType': 'EQUITY',
 'currentPrice': 508.96,
 'targetHighPrice': 870.0,
 'targetLowPrice': 440.0,
 'targetMeanPrice': 577.26135,
 'targetMedianPrice': 575.0,
 'recommendationMean': 1.32727,
 'recommendationKey': 'strong_buy',
 'numberOfAnalystOpinions': 52,
 'totalCash': 76842999808,
 'totalCashPerShare': 10.348,
 'ebitda': 194237005824,
 'totalDebt': 128812998656,
 'quickRatio': 1.099,
 'currentRatio': 1.23,
 'totalRevenue': 331839012864,
 'debtToEquity': 29.118,
 'revenuePerShare': 44.668,
 'returnOnAssets': 0.14088,
 'returnOnEquity': 0.34039003,
 'grossProfits': 225465008128,
 'freeCashflow': 16545500160,
 'operatingCashflow': 182934994944,
 'earningsGrowth': 0.317,
 'revenueGrowth': 0.177,
 'grossMargins': 0.67944,
 'ebitdaMargins': 0.58534,
 'operatingMargins': 0.45111,
 'financialCurrency': 'USD',
 'symbol': 'MSFT',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Delayed Quote',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'epsTrailingTwelveMonths': 17.97,
 'epsForward': 23.67588,
 'epsCurrentYear': 19.75972,
 'priceEpsCurrentYear': 25.75745,
 'fiftyDayAverageChange': 28.707,
 'fiftyDayAverageChangePercent': 0.059774745,
 'twoHundredDayAverageChange': 76.6611,
 'twoHundredDayAverageChangePercent': 0.17733356,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '1.3 - Strong Buy',
 'cryptoTradeable': False,
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 511108200000,
 'preMarketChange': -1.7099915,
 'preMarketChangePercent': -0.33597758,
 'preMarketPrice': 507.25,
 'regularMarketChange': -0.26001,
 'regularMarketChangePercent': -0.0510604,
 'regularMarketPrice': 508.96,
 'regularMarketDayRange': '502.4 - 513.64',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 29345579,
 'fiftyTwoWeekLowChange': 159.75998,
 'fiftyTwoWeekLowChangePercent': 0.45750278,
 'fiftyTwoWeekRange': '349.2 - 553.72',
 'fiftyTwoWeekHighChange': -44.75998,
 'fiftyTwoWeekHighChangePercent': -0.080835044,
 'fiftyTwoWeekChangePercent': -1.7356873,
 'dividendDate': 1796860800,
 'earningsTimestamp': 1785355200,
 'earningsTimestampStart': 1793217600,
 'earningsTimestampEnd': 1793217600,
 'earningsCallTimestampStart': 1785360600,
 'earningsCallTimestampEnd': 1785360600,
 'isEarningsDateEstimate': True,
 'corporateActions': [],
 'preMarketTime': 1790763536,
 'regularMarketTime': 1790712000,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_21835',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'shortName': 'Microsoft Corporation',
 'longName': 'Microsoft Corporation',
 'marketState': 'PRE',
 'displayName': 'Microsoft',
 'trailingPegRatio': 1.6173}

In [2]:
#5일간의 주가 데이터 가져오기
hist = msft.history(period="5d")
display(hist)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-09-23 00:00:00-04:00,500.760010,509.440002,495.880005,500.589996,19445600,0.0,0.0
2026-09-24 00:00:00-04:00,495.070007,498.899994,491.220001,497.929993,16657600,0.0,0.0
2026-09-25 00:00:00-04:00,499.040009,519.400024,497.250000,516.169983,38193100,0.0,0.0
2026-09-28 00:00:00-04:00,505.470001,513.330017,502.220001,509.220001,19626900,0.0,0.0
2026-09-29 00:00:00-04:00,508.309998,513.640015,502.399994,508.959991,21326100,0.0,0.0

In [3]:
#해당 종목에 대한 애널리스트들의 분석 결과 확인하기
msft.recommendations

  period  strongBuy  buy  hold  sell  strongSell
0     0m         14   39     2     0           0
1    -1m         14   38     3     0           0
2    -2m         14   40     3     0           0
3    -3m         13   41     3     0           0